### ISSUE TITLE
DS-1000 Accuracy is 0

### ISSUE THREAD

**Issue by TimeLovercc** [hongcheki/sweet-watermark#10]
I've used the scripts in scripts/main/. My model is starcode2-3B. I just find that the accuracy is 0. Is there any error in the code?

**Comment by thynl** [comment]
Hi, our codebase is SWEET watermark on [bigcode-evaluation-harness](https://github.com/bigcode-project/bigcode-evaluation-harness) repository.
Could you use  that repository's environment when detecting the watermark & evaluating the code performance (generation doesn't matter) and tell me if it solves the problem?

```# python version must be 3.7.10
pip install -e ".[ds1000]" # installs all additional dependencies except PyTorch
# torch==1.12.1 required. Download version with relevant GPU support etc., e.g.,
pip install torch==1.12.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116

# to suppress any tensorflow optimization warnings, 
# precede call to "accelerate launch" with "TF_CPP_MIN_LOG_LEVEL=3"

# on some systems, tensorflow will attempt to allocate all GPU memory
# to its process at import which will raise a CUDA out-of-memory error
# setting "export TF_FORCE_GPU_ALLOW_GROWTH=true" resolves this
```

**Comment by TimeLovercc** [comment]
Thank you for your reply!
