### ISSUE TITLE
missing attribute 'hash_key'

### ISSUE THREAD

**Issue by satori2017** [hongcheki/sweet-watermark#2]
File "sweet-watermark/lm_eval/generation.py", line 79, in parallel_generations
    hash_key=args.hash_key,
AttributeError: 'Namespace' object has no attribute 'hash_key'
Does this attribute exist in args?

**Comment by hongcheki** [comment]
Sorry for late reply.

We are using default hash key value written in line 38 of "watermark.py" so there is no `hash_key` attribute in args.

We will update it, thank you.
