### ISSUE TITLE
about the detection

### ISSUE THREAD

**Issue by LeoStrange26** [hongcheki/sweet-watermark#3]
I'm a bit confused about how to detect the watermark: in the detection stage, you can only get the text and split it into tokens. How can you get the entroy of the a token?

**Comment by hongcheki** [comment]
Sorry for the late reply,

As written here (https://github.com/hongcheki/sweet-watermark/blob/master/lm_eval/evaluator.py#L141), the tokenized text is fed to the model, and entropy values are calculated for each token.

I hope this is an appropriate reply to your question.

**Comment by Sai-Ashish** [comment]
We do not have access to the LLM that generated the text right? Are you using a proxy LLM?
