### ISSUE TITLE
missing attribute dataset

### ISSUE THREAD

**Issue by satori2017** [hongcheki/sweet-watermark#4]
Traceback (most recent call last):
  File "sweet-watermark/lm_eval/tasks/mbpp.py", line 47, in get_dataset
    dataset = self.dataset["test"]
AttributeError: 'MBPP' object has no attribute 'dataset'
Similiar error('HuamnEval' object has no attribute 'dataset') occurs when running generation on "HumanEval"

**Comment by hongcheki** [comment]
Sorry for late response.

Do you have still same problem? Would you check your `datasets` version?

Mine is `datasets==2.16.1`.

`pip freeze | grep datasets`

**Comment by lwind233** [comment]
https://github.com/bigcode-project/bigcode-evaluation-harness/issues/131

execute 'huggingface-cli login'
