### ISSUE TITLE
Hash key

### ISSUE THREAD

**Issue by killiganni** [hongcheki/sweet-watermark#7]
Hello! Could you please explain why the hash key argument was removed from the generation process (but it is still there in evaluation code)? How is it possible now to detect watermarked text without the hash key? Thank you.

**Comment by hongcheki** [comment]
Sorry for late response.

The hash key arguments in `evaluator.py` should had been removed.

We used the same hash key value in the paper as in the code right now (i.e., written in https://github.com/hongcheki/sweet-watermark/blob/master/watermark.py#L38)

Thank you for your interest!
